spring.application.name=demo

# Configuracion H2
spring.datasource.url=jdbc:h2:file:./data/demo-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# DataLoader configuration
app.dataloader.enabled=true

# para depurar errores
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
