DROP TABLE EMPRESA;

CREATE TABLE IF NOT EXISTS EMPRESA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    NIF VARCHAR(20) NOT NULL,
    DIRECCION_SOCIAL VARCHAR(255) NOT NULL,
    RAZON_SOCIAL VARCHAR(100) NOT NULL,
    CAPITAL_SOCIAL DECIMAL(10,2) NOT NULL,
    FECHA_CONSTITUCION DATE NOT NULL
);
